# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FBPOC' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'

  # Pods for FBPOC

  target 'FBPOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FBPOCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
